[phases.setup]
nixPkgs = ["php82", "nginx", "libmysqlclient"]
nixLibs = ["libmysqlclient"]

[phases.install]
cmds = ["mkdir -p /app/pp-media /app/pp-content"]

[start]
cmd = "php-fpm -D && nginx -c /app/nginx.template.conf -g 'daemon off;'"

[staticAssets]
"/" = "."
